# Generated by Django 5.0 on 2023-12-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=128)),
                ('news_img', models.TextField(max_length=3000)),
                ('news_desc', models.TextField(max_length=2000)),
                ('news_tag', models.CharField(max_length=128)),
            ],
        ),
    ]
