# Generated by Django 5.0 on 2023-12-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='news_token',
            field=models.CharField(default='3d08a240629d6620473ee317ee72ca5e', max_length=32),
        ),
    ]
